"""Compile the real firmware CMD parser on the host and test it.

    python firmware/tests/run_cmd_parse_tests.py

No ESP-IDF, no board, no third-party Python packages. Two things are checked:

* malformed packets are rejected — the belt's whole trust boundary is this
  parser, so its rejection paths deserve a test that runs on every commit, and
* the Python encoder in ``laptop/protocol.py`` and the C parser agree, using
  golden packets generated here from the actual haptic profile.  A wire-format
  change on one side without the other now fails the build instead of producing
  a belt that buzzes the wrong way at a demo.

``config.h`` pulls in two ESP-IDF driver headers for GPIO and LEDC constants.
They are stubbed in a temporary directory rather than the parser being changed
to avoid them, so what is compiled here is byte-for-byte the firmware source.
"""
from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
FIRMWARE_MAIN = REPO_ROOT / "firmware" / "main"
TEST_SOURCE = pathlib.Path(__file__).with_name("cmd_parse_host_test.c")

sys.path.insert(0, str(REPO_ROOT))

# Only the constants config.h actually uses. Deliberately minimal: a stub that
# grows is a stub that starts hiding real build breakage.
GPIO_STUB = """#pragma once
#include <stdint.h>
typedef int gpio_num_t;
#define GPIO_NUM_13 13
#define GPIO_NUM_21 21
"""

LEDC_STUB = """#pragma once
#include <stdint.h>
typedef int ledc_channel_t;
#define LEDC_TIMER_8_BIT 8
"""


def golden_cases():
    """Every direction x class pattern, encoded as both v2 and v3."""
    from laptop.haptic import DANGER_LABELS, DEFAULT_PROFILE, build_command
    from laptop.protocol import (
        CMD_VERSION_V2,
        CMD_VERSION_V3,
        DIR_BACK,
        DIR_FRONT,
        DIR_LEFT,
        DIR_RIGHT,
        decode,
        direction_name,
        encode,
    )

    cases = []
    for direction in (DIR_LEFT, DIR_RIGHT, DIR_FRONT, DIR_BACK):
        for label in DANGER_LABELS:
            for confidence in (0.50, 0.75, 1.00):
                command = build_command(label, confidence, direction, DEFAULT_PROFILE)
                assert command is not None, (label, direction)
                for version in (CMD_VERSION_V3, CMD_VERSION_V2):
                    packet = encode(1, command, version)
                    # Decode with the Python decoder too: the expectations handed
                    # to C come from the wire bytes, not from the pre-encoding
                    # command, so an encoder bug cannot be masked by reusing the
                    # same in-memory object on both sides.
                    played = decode(packet).command
                    cases.append({
                        "name": f"v{version}-{direction_name(direction)}-{label}"
                                f"-c{int(confidence * 100)}",
                        "data": packet,
                        "version": version,
                        "direction": played.direction,
                        "intensity": played.intensity,
                        "steps": played.steps,
                    })
    return cases


def render_golden_header(cases) -> str:
    from laptop.protocol import PATTERN_MAX_STEPS, V3_MAX_BYTES

    lines = [
        "// GENERATED by firmware/tests/run_cmd_parse_tests.py -- do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    int len;",
        f"    uint8_t data[{V3_MAX_BYTES}];",
        "    int version, direction, intensity, n_steps;",
        f"    uint8_t masks[{PATTERN_MAX_STEPS}];",
        f"    uint16_t on_ms[{PATTERN_MAX_STEPS}], off_ms[{PATTERN_MAX_STEPS}];",
        "} golden_case_t;",
        "",
        "static const golden_case_t GOLDEN[] = {",
    ]
    for case in cases:
        data = ", ".join(f"0x{byte:02x}" for byte in case["data"])
        masks = ", ".join(str(step.mask) for step in case["steps"]) or "0"
        on_ms = ", ".join(str(step.on_ms) for step in case["steps"]) or "0"
        off_ms = ", ".join(str(step.off_ms) for step in case["steps"]) or "0"
        lines += [
            "    {",
            f'        .name = "{case["name"]}",',
            f'        .len = {len(case["data"])},',
            f"        .data = {{{data}}},",
            f'        .version = {case["version"]},',
            f'        .direction = {case["direction"]},',
            f'        .intensity = {case["intensity"]},',
            f'        .n_steps = {len(case["steps"])},',
            f"        .masks = {{{masks}}},",
            f"        .on_ms = {{{on_ms}}},",
            f"        .off_ms = {{{off_ms}}},",
            "    },",
        ]
    lines += [
        "};",
        "#define GOLDEN_COUNT (sizeof(GOLDEN) / sizeof(GOLDEN[0]))",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default="cc", help="C compiler to use")
    parser.add_argument("--keep", action="store_true",
                        help="keep the generated build directory and print its path")
    args = parser.parse_args()

    cases = golden_cases()
    # mkdtemp rather than TemporaryDirectory(delete=...): that keyword needs
    # Python 3.12 and this must run on the 3.11 the CI workflow pins.
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="meit-cmd-parse-"))
    try:
        (tmp / "driver").mkdir()
        (tmp / "driver" / "gpio.h").write_text(GPIO_STUB, encoding="utf-8")
        (tmp / "driver" / "ledc.h").write_text(LEDC_STUB, encoding="utf-8")
        (tmp / "golden.h").write_text(render_golden_header(cases), encoding="utf-8")

        binary = tmp / "cmd_parse_test"
        compile_cmd = [
            args.cc, "-std=c11", "-Wall", "-Wextra", "-Werror", "-O1",
            f"-I{tmp}", f"-I{FIRMWARE_MAIN}",
            str(TEST_SOURCE), str(FIRMWARE_MAIN / "cmd_parse.c"),
            "-o", str(binary),
        ]
        print("compiling:", " ".join(compile_cmd[:4]), "...")
        compiled = subprocess.run(compile_cmd, capture_output=True, text=True)
        if compiled.returncode != 0:
            print(compiled.stdout)
            print(compiled.stderr, file=sys.stderr)
            return compiled.returncode
        if args.keep:
            print(f"build directory: {tmp}")

        result = subprocess.run([str(binary)], capture_output=True, text=True)
        print(result.stdout, end="")
        if result.stderr:
            print(result.stderr, file=sys.stderr, end="")
        return result.returncode
    finally:
        if not args.keep:
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
